[project]
name = "awr2rpi-readdata-py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy",
    "pyserial",
    "pyqtgraph",
    "matplotlib",
]
